# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-23 11:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0002_auto_20170116_1048'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingPackage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('price', models.IntegerField()),
                ('num_judgements', models.IntegerField()),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
            ],
        ),
    ]
