# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-06-04 16:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_pricingpackage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courtmodel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
